### ISSUE TITLE
Unable to translate

### ISSUE THREAD

**Issue by sodalimes** [nextcloud/translate#30]
I have downloaded the languages, when I go to run it, I get this error. 
![image](https://github.com/nextcloud/translate/assets/108687422/39e0dc67-0302-4eab-9ed6-b06a3288e0ae)

**Comment by sodalimes** [comment]
I also receive [translate] Warning: sh: 1: exec: : Permission denied as well

**Comment by marcelklehr** [comment]
Hello @sodalimes 

Does your machine or execution environment (e.g. docker) fullfil the requirements listed in the README?


- x86 CPU
- GNU lib C (musl is not supported)

**Comment by kizm0** [comment]
Hey @sodalimes i also had the error message exec::Permission denied, i checked if node was installed in the directory /apps/translate/bin ... it was not due to firewall restrictions, after my nextcloud instance could access nodejs.org, node was installed in the bin directory and the translate app works as expected
