### ISSUE TITLE
Translate leads Apache web server crash under certain conditions

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/translate#32]
Running translate in LXD containers. I noticed that sometimes a translation operations leads to a memory runaway and a (probably related) Apache web server crash.

The translation is triggered from the Text app with a text of around 300 words and 1600 characters. Translation is English to Spanish, with the small model.

I'm NC Server 27.1.2 and 1.1.6.

With the container assigned 1GiB of memory the Apache server crashes.
With the container assigned 2GiB of memory there is no crash.
With the container assigned 4GiB of memory there is no crash.

In all cases the translation fails with a "Failed to translate from en to es using provider Opus models by the University of Helsinki", that is not propagated to the user.

So some questions:

- I understand that the model must be loaded in memory. Is there an upper estimate of the consumed memory and does it depend on the size of the text to translate as well, or just the model size?
- Should the system get the memory available and refusing to start the operation if not enough is available?
- Why errors are not properly propagated to the user?

**Comment by marcelklehr** [comment]
> With the container assigned 1GiB of memory the Apache server crashes.

The models need around 1GB of memory on their own. If you have a memory limit of 1GB and other things running (like Apache), something will get killed with an out of memory error.

> Why errors are not properly propagated to the user?

Details of what went wrong are not propagated to the end user because they include details of the system and the error is not one for the end user to mitigate but for the admin.
