### ISSUE TITLE
Unable to install Translate

### ISSUE THREAD

**Issue by louim-lbs** [nextcloud/translate#6]
Hi,
I'm trying to install translate on NC 26, and I have this error in the Nextcloud logs: 

```
foreach() argument must be of type array\|object, int given at /config/www/nextcloud/apps/translate/lib/Helper/TAR.php#208 |  

```
I'm using PHP 8.0

**Comment by marcelklehr** [comment]
Seems like it fails to download the node executable. Does nextcloud have internet access? What's your processor architecture?

**Comment by hjbeckers** [comment]
NC 26.01 runs on a Raspberry P4 with 8 GB RAM. Node.js v12.22.9. is installed. php is version 8.1.2-1ubuntu2.11.

I have  a similiar problem: The app is installed;  ~10 GB of language models are downloaded (an information on the HP would be nice.) Trying to translate something, the cursor/mouse pointer changes for 2 or 3 seconds and in the log I get the following errors (in reverse order):

Exception: Typed property OCA\IntegrationLibreTranslate\LibretranslateProvider::$translator must not be accessed before initialization in file '/var/www/html/oc/apps/integration_libretranslate/lib/LibretranslateProvider.php' line 150		vor einer Minute

Fehler	integration_libretranslate	Exception: en is not an available language.		vor einer Minute

Fehler	PHP	foreach() argument must be of type array|object, null given at /var/www/html/oc/apps/integration_libretranslate/vendor/jefs42/libretranslate/src/LibreTranslate.php#119		vor einer Minute

Fehler	integration_libretranslate	Exception: en is not an available language.		vor einer Minute

Fehler	PHP	foreach() argument must be of type array|object, null given at /var/www/html/oc/apps/integration_libretranslate/vendor/jefs42/libretranslate/src/LibreTranslate.php#119		vor einer Minute

The second "Exception: en is not ..." should read "Exception FR is not ..." because on a second try I selected FRench in the destination field.

Part of my /etc/os-release file:
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian

**Comment by kevinkuan1969** [comment]
Nextcloud - 26.01
PHP - 8.1
Node.js v12.22.9
Translate 1.1.3

Similar issue where nothing display and with the following error log:

<html>
<body>


Warning | no app in context | RuntimeException: Translate process failed/var/www/nextcloud/apps/translate/lib/Provider/Translation.php - line 66:OCA\Translate\Service\TranslateService->seq2seq()/var/www/nextcloud/lib/private/Translation/TranslationManager.php - line 76:OCA\Translate\Provider\Translation->translate()/var/www/nextcloud/core/Controller/TranslationApiController.php - line 72:OC\Translation\TranslationManager->translate()/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 230:OC\Core\Controller\TranslationApiController->translate()/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 137:OC\AppFramework\Http\Dispatcher->executeController()/var/www/nextcloud/lib/private/AppFramework/App.php - line 183:OC\AppFramework\Http\Dispatcher->dispatch()/var/www/nextcloud/lib/private/Route/Router.php - line 315:OC\AppFramework\App::main()/var/www/nextcloud/ocs/v1.php - line 64:OC\Route\Router->match()/var/www/nextcloud/ocs/v2.php - line 23:require_once("/var/www/nextcloud/ocs/v1.php")
-- | -- | --



</body>
</html>

Warning	translate	node:internal/errors:484 ErrorCaptureStackTrace(err); ^ Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'onnxruntime-node' imported from /var/www/nextcloud/apps/translate/src/seq2seq.mjs at new NodeError (node:internal/errors:393:5) at packageResolve (node:internal/modules/esm/resolve:860:9) at moduleResolve (node:internal/modules/esm/resolve:909:20) at defaultResolve (node:internal/modules/esm/resolve:1124:11) at nextResolve (node:internal/modules/esm/loader:163:28) at ESMLoader.resolve (node:internal/modules/esm/loader:841:30) at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18) at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40) at link (node:internal/modules/esm/module_job:75:36) { code: 'ERR_MODULE_NOT_FOUND' } Node.js v18.12.1		10 minutes ago

**Comment by marcelklehr** [comment]
> IntegrationLibreTranslate

@hjbeckers You're in the wrong repository. This is the translate app. You want to file this issue with the integration_libretranslate app.

> 1.1.3

Should be fixed with v1.1.4

**Comment by louim-lbs** [comment]
I upgraded to version 26.0.2 and the installation process worked (though the app doesn't work yet, even after downloading models, maybe another issue). Should I close the issue?

**Comment by bcutter** [comment]
```
  | translate | GuzzleHttp\Exception\ServerException: Server  error: `GET  https://nodejs.org/dist/v18.12.1/node-v18.12.1-linux-armv7l.tar.gz`  resulted in a `500 Internal Server Error` response: ...
```
and
```
no app in context | Exception: Downloading of node binary failed
```

Well, running on a Raspberry Pi 4 - which obviously does not match the x86 CPU requirement listed in the app description. Why can it be installed at all? Apps do have requirements check, do they? At least PHP, Nextcloud version and OS type (32/64 bit) as far as I am aware of. Looks like this app would need a processor type filter to block the install process for not supported platforms.

**Comment by marcelklehr** [comment]
> though the app doesn't work yet, even after downloading models, maybe another issue). Should I close this issue?

Yes, please open a new issue for the non-working thing.

**Comment by marcelklehr** [comment]
> Why can it be installed at all? Apps do have requirements check, do they? At least PHP, Nextcloud version and OS type (32/64 bit) as far as I am aware of. Looks like this app would need a processor type filter to block the install process for not supported platforms.

Yes, this does not exist.
